from django.contrib import admin
from django.urls import path,include
from . import views
urlpatterns = [

    path("",views.index,name="index"),
    path("apps-chat.html",views.app_chat),
    path("advanced-animation.html",views.advance_animation),
    path("apps-contact-list.html",views.app_contact,name="app-contact"),
    path("apps-calendar.html",views.app_calendar,name="app-calendar"),
    path("apps-files.html",views.app_files,name="app-files"),
    path("apps-invoice.html",views.app_invoice,name="app-invoice"),
    path("apps-tasks.html",views.app_task,name="app-task"),
    path("apps-project-overview.html",views.app_overview,name="app-overview"),
    path("apps-project-projects.html",views.app_project,name="app-project"),
    path("apps-project-board.html",views.app_board,name="app-board"),
    path("apps-project-teams.html",views.app_teams,name="app-teams"),
    path("apps-project-files.html",views.app_project_files,name="app-project-files"),
    path("apps-new-project.html",views.app_new_project,name="app-new-project"),
    path("apps-ecommerce-products.html",views.e_product,name="e-product"),
    path("apps-ecommerce-product-list.html",views.e_product_list),
    path("apps-ecommerce-product-detail.html",views.e_product_detail,name="eproduct-detail"),
    path("apps-ecommerce-cart.html",views.e_cart,name="e_cart"),
    path("apps-ecommerce-checkout.html",views.e_checkout,name="e-checkout"),
    # path("auth-login.html",views.a_login,name="a-login"),
    path("auth-login.html",views.LoginView.as_view()),
    path("auth-register.html",views.Register.as_view()),
    # path("auth-register.html",views.a_register,name="a-register"),
    path("auth-recover-pw.html",views.a_recover,name="a-recover"),
    path("auth-lock-screen.html",views.a_lockscreen,name="a-lockscreen"),
    path("auth-404.html",views.error404,name="404"),
    path("auth-500.html",views.error500,name="500"),
    path("ui-alerts.html",views.ui_alert,name="ui-alert"),
    path("ui-avatar.html",views.ui_avtar,name="ui-avtar"),
    path("ui-buttons.html",views.ui_buttons,name="ui-buttons"),
    path("ui-badges.html",views.ui_badges,name="ui-badges"),
    path("ui-cards.html",views.ui_cards),
    path("ui-carousels.html",views.ui_carousels),
    path("ui-check-radio.html",views.ui_checkradio),
    path("ui-dropdowns.html",views.ui_dropdown),
    path("ui-grids.html",views.ui_grid),
    path("ui-images.html",views.ui_images),
    path("ui-list.html",views.ui_list),
    path("ui-modals.html",views.ui_modals),
    path("ui-navbar.html",views.ui_navbar),
    path("ui-navs.html",views.ui_navs),
    path("ui-paginations.html",views.ui_paginations),
    path("ui-progress.html",views.ui_progress),
    path("ui-popover-tooltips.html",views.ui_tool),
    path("ui-spinners.html",views.ui_spinners),
    path("ui-tabs-accordions.html",views.ui_accordions),
    path("ui-toasts.html",views.ui_toasts),
    path("ui-typography.html",views.ui_typography),
    path("ui-videos.html",views.ui_videos),
    path("widgets.html",views.ui_widgets),
    path("advanced-clipboard.html",views.advance_clipboard),
    path("advanced-highlight.html",views.advance_highlight),
    path("advanced-idle-timer.html",views.advance_timer),
    path("advanced-kanban.html",views.advance_kanban),
    path("advanced-lightbox.html",views.advance_lightbox),
    path("advanced-nestable.html",views.advance_nestable),
    path("advanced-rangeslider.html",views.advance_rangeslider),
    path("advanced-ratings.html",views.advance_rating),
    path("advanced-ribbons.html",views.advance_ribbons),
    path("advanced-sessions.html",views.advance_session),
    path("advanced-sweetalerts.html",views.advance_sweetalerts),
    path("forms-advanced.html",views.form_advance),
    path("froms-editors.html",views.form_editors),
    path("forms-elements.html",views.form_elements),
    path("forms-repeater.html",views.form_repeater),
    path("forms-uploads.html",views.form_uploads),
    path("forms-validation.html",views.form_validation),
    path("forms-wizard.html",views.form_wizard),
    path("forms-x-editable.html",views.form_editable),
    path("horizontal-index.html",views.horizontal_index),
    path("horizontal-stater.html",views.horizontal_starter),
    path("horizontal-top-dark.html",views.horizontal_dark),
    path("pages-blogs.html",views.page_blogs),
    path("pages-faqs.html",views.page_faq),
    path("pages-pricing.html",views.page_price),
    path("pages-profile.html",views.page_profile),
    path("pages-starter.html",views.page_starter),
    path("pages-timeline.html",views.page_timeline),
    path("pages-treeview.html",views.page_treeview),
    path("sales-index.html",views.sales_index),
    path("tables-basic.html",views.table_basic),
    path("tables-datatable.html",views.table_datatable),
    path("tables-editable.html",views.table_editable),
    path("tables-responsive.html",views.table_responsive),
    path("icons-dripicons.html",views.icon_dripicons),
    path("icons-feather.html",views.icon_feather),
    path("icons-fontawesome.html",views.icon_fontawesome),
    path("icons-materialdesign.html",views.icon_materialdesign),
    path("icons-themify.html",views.icon_themify),
    path("icons-typicons.html",views.icon_typicons),
    path("maps-google.html",views.map_google),
    path("maps-leaflet.html",views.map_leaflet),
    path("maps-vector.html",views.map_vector),
    path("email-templates-alert.html",views.email_alert),
    path("email-templates-basic.html",views.email_basic),
    path("email-templates-billing.html",views.email_billing),
    path("demo-rtl.html",views.demo_rtl),
    path("demo-rtl-horizontal.html",views.demo_rtl_horizontal),
    path("demo-navy.html",views.demo_navy),
    path("demo-dark.html",views.demo_dark),
    path("demo-dark-horizontal.html",views.demo_dark_horizontal),
    path("dark-index.html",views.dark_index),
    path("dark-horizontal-index.html",views.dark_horizontal_index),
    path("charts-apex.html",views.chart_apex),
    path("charts-chartjs.html",views.chart_js),
    path("charts-flot.html",views.chart_flot),
    path("charts-morris.html",views.chart_morris),
    path("apps-email-inbox.html",views.app_email_inbox),
    path("apps-email-read.html",views.app_email_read),
    path("logout",views.logouts,name="logout"),








    
    
]
